kind: pipeline
name: managementweb
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:slim
    depends_on: [clone]
    commands:
      - "npm i && npm run build"
    
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
