kind: pipeline
name: managementweb
type: docker

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: modules
    host:
      path: /root/node/modules:/drone/src/node_modules
  - name: build
    host:
      path: /root/www/manageweb:/drone/src/build

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:slim
    depends_on: [clone]
    volumes:
      - name: modules
        path: /root/node/modules:/drone/src/node_modules
      - name: build
        path: /root/www/manageweb:/drone/src/build
    commands:
      - npm config set registry https://registry.npm.taobao.org # 切换淘宝镜像
      - "npm i && npm run build"
    