kind: pipeline
name: managementweb
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: node:slim
    depends_on: [clone]
    commands:
      - pwd # 查看当前目录
      - npm config set registry https://registry.npm.taobao.org # 切换淘宝镜像
      - "npm i && npm run build"
    
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
