kind: pipeline
name: management
type: docker

platform:
  os: linux
  arch: amd64
steps:
  - name: docker
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f Dockerfile -t managementweb .
  - name: pack
    image: managementweb
    environment:
      IMAGE: managementweb
      NGINX_PORT: 80
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: html
        path: /data/front:/usr/share/nginx/html
      - name: logs
        path:  /usr/local/nginx/logs:/var/log/nginx
      - name: nginx
        path:  /usr/local/nginx:/etc/nginx/
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
