kind: pipeline
name: managementweb
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: pack
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f Dockerfile -t managementweb .
  - name: build
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: manageweb
        path: /root/www/manageweb/:/var/build
      - name: node
        path: /root/node/manageweb/:/src/node_modules
    commands:
      - dir
      # - docker stop managementweb
      # - docker rm managementweb
      # - docker build -f Dockerfile -t managementweb .
      # - docker run -d -p 8088:80  -v /usr/local/nginx:/etc/nginx/ -v /usr/local/nginx/logs:/var/log/nginx --name managementweb managementweb 
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
