kind: pipeline
name: managementweb
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - "docker build -f Dockerfile -t managementweb ."
  - name: run
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - "dir"
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
