kind: pipeline
name: management
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: pack
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -f Management.WebApi/Dockerfile -t management .
  - name: push
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: www
        path: /var/www
    commands:
      - docker stop managementweb 
      - docker rm managementweb
      - docker run -d -p 8001:80 --name managementweb managementweb:latest
      - docker cp managementweb:/var/www/ /var/www
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
