kind: pipeline
name: managementweb
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    when:
      branch:
        - master
    image: docker:dind
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: manageweb
        path: /root/www/manageweb/:/src/build
      - name: node
        path: /root/node/manageweb/:/src/node_modules
    commands:
      # - docker stop managementweb
      # - docker rm managementweb
      - docker build -f Dockerfile -t managementweb .
      - docker run  -v /root/www/manageweb/:/src/build -v /root/node/manageweb/:/src/node_modules --name managementweb managementweb 
      - docker exec -it managementweb /bin/sh ./build.sh
      - docker rm managementweb
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
