kind: pipeline
name: managementweb
type: docker

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    when:
      branch:
        - master
    image: managementweb
    environment:
      IMAGE: managementweb
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: manageweb
        path: /root/www/manageweb/:/src/build
      - name: node
        path: /root/node/manageweb/:/src/node_modules
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
