version: '3'
services:
  managementweb:
    build: ./
    restart: always
    container_name: managementweb
    image: managementweb
    ports:
    - 80:80
    - 443:443
    volumes:
    - /data/front:/usr/share/nginx/html
    - /root/nginx/logs:/var/log/nginx
    - /root/nginx:/etc/nginx/
    environment:
    - NGINX_PORT=80
    privileged: true