version: '3'
services:
  web:
    build: ./
    restart: always
    container_name: web
    image: web
    volumes:
      - /root/html/:/src/build
      - /root/node/web/:/src/node_modules
    ports:
      - 80:80
      - 443:443
    command: /bin/bash -c "npm i &&npm run build"